spring.application.name=indira
spring.datasource.url=jdbc:postgresql://localhost:5432/indira_db
spring.datasource.username=postgres
spring.datasource.password=tortugafeliz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id= identificador
spring.security.oauth2.client.registration.google.client-secret= Secreto

spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# Internacionalización
spring.messages.basename=i18n/index/messages,i18n/login/messages,i18n/registro/messages,i18n/completar-perfil/messages,i18n/catalogo/messages,i18n/detalle/messages,i18n/carrito/messages,i18n/pago/messages,i18n/sin-permisos/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
# key
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl_indira.p12
server.ssl.key-store-password=INDIRA2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=ssl-indira

