spring.application.name=indira
spring.datasource.url=jdbc:postgresql://localhost:5432/indira_db
spring.datasource.username=postgres
spring.datasource.password=tortugafeliz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id= identificador
spring.security.oauth2.client.registration.google.client-secret= Secretito
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com